services:
  pocket-software-b5e58e:
    build:
      context: .
      args:
        NEXT_PUBLIC_GA_ID: ${NEXT_PUBLIC_GA_ID}
        NEXT_PUBLIC_CALCOM_URL: ${NEXT_PUBLIC_CALCOM_URL}
        NEXT_PUBLIC_CALCOM_EVENT_SLUG: ${NEXT_PUBLIC_CALCOM_EVENT_SLUG}
    container_name: pocket-software-b5e58e
    restart: unless-stopped
